### ISSUE TITLE
object is not a function / forEach of undefined

### ISSUE THREAD

**Issue by moshmage** [unlight/thesaurus-service#1]
```
var synonym = require('thesaurus-service');
synonym('word').on('data'....);
```

produces:

```
TypeError: object is not a function
    at /home/joagon/workspace/intranetv02/app/server/api/search-api.js:53:13
    at Array.forEach (native)
    at searchFor (/home/joagon/workspace/intranetv02/app/server/api/search-api.js:52:16)
    at Layer.handle [as handle_request] (/home/joagon/workspace/intranetv02/app/server/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/joagon/workspace/intranetv02/app/server/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/home/joagon/workspace/intranetv02/app/server/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/joagon/workspace/intranetv02/app/server/node_modules/express/lib/router/layer.js:95:5)
    at /home/joagon/workspace/intranetv02/app/server/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/home/joagon/workspace/intranetv02/app/server/node_modules/express/lib/router/index.js:330:12)
    at next (/home/joagon/workspace/intranetv02/app/server/node_modules/express/lib/router/index.js:271:10)
    at SessionStrategy.strategy.pass (/home/joagon/workspace/intranetv02/app/server/node_modules/passport/lib/middleware/authenticate.js:318:9)
    at SessionStrategy.authenticate (/home/joagon/workspace/intranetv02/app/server/node_modules/passport/lib/strategies/session.js:71:10)
    at attempt (/home/joagon/workspace/intranetv02/app/server/node_modules/passport/lib/middleware/authenticate.js:341:16)
    at authenticate (/home/joagon/workspace/intranetv02/app/server/node_modules/passport/lib/middleware/authenticate.js:342:7)
    at Layer.handle [as handle_request] (/home/joagon/workspace/intranetv02/app/server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/joagon/workspace/intranetv02/app/server/node_modules/express/lib/router/index.js:312:13)
    at /home/joagon/workspace/intranetv02/app/server/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/joagon/workspace/intranetv02/app/server/node_modules/express/lib/router/index.js:330:12)
    at next (/home/joagon/workspace/intranetv02/app/server/node_modules/express/lib/router/index.js:271:10)
    at initialize (/home/joagon/workspace/intranetv02/app/server/node_modules/passport/lib/middleware/initialize.js:53:5)
    at Layer.handle [as handle_request] (/home/joagon/workspace/intranetv02/app/server/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/joagon/workspace/intranetv02/app/server/node_modules/express/lib/router/index.js:312:13)

```

This was fixed by using the `stream()` function like so `synonym.stream('word')` but then it produces `forEach of undefined`

```
var synonym = require('thesaurus-service');
synonym.stream('word').on('data'....);
```

```
/home/joagon/workspace/intranetv02/app/server/node_modules/thesaurus-service/dist/altervistaorg.js:31
            jsonResponse.forEach(_this._parseList, _this);
                        ^
TypeError: Cannot read property 'forEach' of undefined
    at Request._callback (/home/joagon/workspace/intranetv02/app/server/node_modules/thesaurus-service/dist/altervistaorg.js:31:25)
    at Request.self.callback (/home/joagon/workspace/intranetv02/app/server/node_modules/thesaurus-service/node_modules/request/request.js:198:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/home/joagon/workspace/intranetv02/app/server/node_modules/thesaurus-service/node_modules/request/request.js:1073:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/home/joagon/workspace/intranetv02/app/server/node_modules/thesaurus-service/node_modules/request/request.js:1019:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

You have any idea what I might be doing wrong?

**Comment by unlight** [comment]
Looks like json response is invalid.
I added error handler in version 1.2 which is on npm or here (this repository branch #master)

**Comment by moshmage** [comment]
@unlight Thanks mate! That did it :+1:
